[general]
    live_config_reload = true

[window]
    opacity = 0.8
    padding = { x = 5, y = 5 }

[font]
    size = 11.0

[font.bold]
    family = "Fira Code"
    style  = "SemiBold"

[font.bold_italic]
    family = "Fira Code"
    style  = "Medium"

[font.italic]
    family = "Fira Code"
    style  = "Retina"

[font.normal]
    family = "Fira Code"
    style  = "Regular"

[cursor]
    blink_interval   = 500
    blink_timeout    = 0
    unfocused_hollow = false
    thickness        = 0.5

[cursor.style]
    shape    = "Block"
    blinking = "Always"

    
